### ISSUE TITLE
Что это за хуйня

### ISSUE THREAD

**Issue by Kamillaova** [ZaIupaMC/zlib#1]
![SB95tRHU](https://user-images.githubusercontent.com/54859825/216846362-8f512655-a760-4c7c-97d3-b13ef24fdb89.gif)

**Comment by AudioAD** [comment]
![image](https://user-images.githubusercontent.com/76812379/216855831-1f6680a2-6f32-4ab9-b299-cc577d072d0c.png)

**Comment by jnvkal** [comment]
![image](https://user-images.githubusercontent.com/123752488/216856559-7b18acf2-326b-45c4-ba5c-c26e91c6e82f.png)
